# Generated by Django 3.1.1 on 2023-01-16 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rttregulation', '0031_merge_20220916_0531'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttproduct', '0008_auto_20220623_1319'),
        ('rttsubstance', '0022_auto_20230110_0624'),
        ('rttnews', '0019_newsupdatelogforassessmentworkflowremove'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('attachment_document', models.FileField(blank=True, null=True, upload_to='media/attachment_document')),
                ('news', models.ManyToManyField(blank=True, related_name='doc_management_news', to='rttnews.News')),
                ('products', models.ManyToManyField(blank=True, related_name='doc_management_products', to='rttproduct.Product')),
                ('regulations', models.ManyToManyField(blank=True, related_name='doc_management_regulations', to='rttregulation.Regulation')),
                ('regulatory_frameworks', models.ManyToManyField(blank=True, related_name='doc_management_frameworks', to='rttregulation.RegulatoryFramework')),
                ('substances', models.ManyToManyField(blank=True, related_name='doc_management_substances', to='rttsubstance.Substance')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_management_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Document Managements',
                'ordering': ('-created',),
            },
        ),
    ]
