# Generated by Django 3.1.1 on 2023-02-08 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttdocumentManagement', '0002_documentmanagementcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocManagementHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default='updated', max_length=20)),
                ('action_field', models.CharField(blank=True, max_length=50)),
                ('prev_value', models.TextField(blank=True)),
                ('curr_value', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('action_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_management', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rttdocumentManagement.documentmanagement')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DocManagementCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_management', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rttdocumentManagement.documentmanagement')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddConstraint(
            model_name='docmanagementcollaborator',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, collaborator__isnull=True), fields=('document_management', 'collaborator'), name='unique_document_management_collaborator'),
        ),
    ]
