# Generated by Django 3.1.1 on 2020-12-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0004_auto_20201105_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='password_expiration',
            field=models.IntegerField(default=0),
        ),
    ]
