# Generated by Django 3.1.1 on 2021-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttproduct', '0004_auto_20201222_2122'),
        ('rttorganization', '0007_auto_20201217_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='organization_industries', to='rttproduct.Industry'),
        ),
    ]
