# Generated by Django 3.1.1 on 2021-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0008_organization_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='groups',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='live_assessment',
            field=models.BooleanField(default=False, help_text='Identify which organization is subscribed to the “live assessment” service', verbose_name='Active live assessment'),
        ),
    ]
