# Generated by Django 3.1.1 on 2021-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0009_auto_20210810_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_active_limits_management_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_active_substance_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='is_active_task_management_module',
            field=models.BooleanField(default=False),
        ),
    ]
