# Generated by Django 3.1.1 on 2021-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0009_auto_20210810_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='public_api_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name', 'public_api_key', 'public_api_secret'), name='unique_organization_public_api_key_secret'),
        ),
    ]
