# Generated by Django 3.1.1 on 2021-10-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0010_auto_20211027_0804'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_organization_public_api_key_secret',
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('public_api_key', 'public_api_secret'), name='unique_organization_public_api_key_secret'),
        ),
    ]
