# Generated by Django 3.1.1 on 2021-12-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0011_auto_20211028_0431'),
        ('rttorganization', '0010_auto_20211027_1326'),
    ]

    operations = [
    ]
