# Generated by Django 3.1.1 on 2023-01-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0013_subscriptiontype_is_active_document_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='max_quota_for_all_documents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='max_quota_for_one_document',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
