# Generated by Django 3.1.1 on 2023-04-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0013_subscriptiontype_is_active_reports_module'),
        ('rttorganization', '0014_auto_20230118_0622'),
    ]

    operations = [
    ]
