# Generated by Django 3.1.1 on 2020-10-19 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttorganization', '0001_initial'),
        ('rttdocument', '0001_initial'),
        ('rttnews', '0001_initial'),
        ('rttproduct', '0001_initial'),
        ('rttregulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrelevance',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rttorganization.organization'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='industries',
            field=models.ManyToManyField(blank=True, to='rttproduct.Industry'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rttnews.newscategory'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_category_topic', to='rttregulation.topic'),
        ),
        migrations.AddField(
            model_name='news',
            name='discharged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discharged_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='documents',
            field=models.ManyToManyField(blank=True, to='rttdocument.Document'),
        ),
        migrations.AddField(
            model_name='news',
            name='material_categories',
            field=models.ManyToManyField(blank=True, related_name='material_category_news', to='rttproduct.MaterialCategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_categories',
            field=models.ManyToManyField(blank=True, to='rttnews.NewsCategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='rttorganization.Organization'),
        ),
        migrations.AddField(
            model_name='news',
            name='product_categories',
            field=models.ManyToManyField(blank=True, related_name='product_category_news', to='rttproduct.ProductCategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='region_news', to='rttregulation.Region'),
        ),
        migrations.AddField(
            model_name='news',
            name='regulations',
            field=models.ManyToManyField(blank=True, related_name='regulation_news', to='rttregulation.Regulation'),
        ),
        migrations.AddField(
            model_name='news',
            name='regulatory_frameworks',
            field=models.ManyToManyField(blank=True, to='rttregulation.RegulatoryFramework'),
        ),
        migrations.AddField(
            model_name='news',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_source', to='rttnews.source'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('title', 'pub_date', 'source'), name='unique_title_pubdate_source'),
        ),
    ]
