# Generated by Django 3.1.1 on 2020-11-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttdocument', '0001_initial'),
        ('rttnews', '0004_auto_20201119_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='news_documents', to='rttdocument.Document'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_categories',
            field=models.ManyToManyField(blank=True, related_name='news_categories', to='rttnews.NewsCategory'),
        ),
    ]
