# Generated by Django 3.1.1 on 2020-12-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0005_auto_20201127_1546'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='news',
            name='unique_title_pubdate_source',
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
