# Generated by Django 3.1.1 on 2021-02-24 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttnews', '0007_auto_20201217_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrelevance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
