# Generated by Django 3.1.1 on 2021-08-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0009_newsrelevancelog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newsrelevance',
            constraint=models.UniqueConstraint(fields=('organization', 'news'), name='unique_news_organization_relevancy'),
        ),
    ]
