# Generated by Django 3.1.1 on 2021-08-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0010_auto_20210826_0514'),
        ('rttnews', '0009_auto_20210810_1332'),
    ]

    operations = [
    ]
