# Generated by Django 3.1.1 on 2021-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0010_auto_20210909_1153'),
        ('rttnews', '0011_merge_20210827_0539'),
    ]

    operations = [
    ]
