# Generated by Django 3.1.1 on 2022-03-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0012_merge_20210921_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrelevancelog',
            name='prev_relevancy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
