# Generated by Django 3.1.1 on 2022-03-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0013_newsanswer_newsquestion_newsquestiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanswer',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rttnews.news'),
            preserve_default=False,
        ),
    ]
