# Generated by Django 3.1.1 on 2022-03-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0014_auto_20220309_1104'),
        ('rttnews', '0013_auto_20220311_0814'),
    ]

    operations = [
    ]
