# Generated by Django 3.1.1 on 2022-04-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0014_newsrelevancelog_parent'),
        ('rttnews', '0015_merge_20220318_1009'),
    ]

    operations = [
    ]
