# Generated by Django 3.1.1 on 2022-06-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0016_merge_20220418_0949'),
        ('rttnews', '0014_automaticfileimportnewssource'),
    ]

    operations = [
    ]
