# Generated by Django 3.1.1 on 2022-07-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0017_merge_20220630_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='review_green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='review_yellow',
            field=models.BooleanField(default=False),
        ),
    ]
