# Generated by Django 3.1.1 on 2022-12-06 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0018_auto_20220705_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdateLogForAssessmentWorkflowRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('active', models.BooleanField(default=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rttnews.news')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
