# Generated by Django 3.1.1 on 2021-12-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='limitattribute',
            name='list_values_when_field_type_is_list_field',
        ),
        migrations.AddConstraint(
            model_name='limitattribute',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('field_type', 'list_field'), models.Q(_negated=True, list_values='')), models.Q(models.Q(_negated=True, field_type='list_field'), ('list_values', '')), _connector='OR'), name='list_values_when_field_type_is_list_field'),
        ),
    ]
