# Generated by Django 3.1.1 on 2021-12-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0002_auto_20211206_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemption',
            name='date_into_force',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exemption',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regulationsubstancelimit',
            name='date_into_force',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
