# Generated by Django 3.1.1 on 2021-12-23 13:25

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0002_auto_20211206_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitUploadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file_name', models.TextField()),
                ('process_type', models.CharField(choices=[('regulation_substance_limit', 'Regulation Substance Limit'), ('exemption', 'Exemption')], default='regulation_substance_limit', max_length=100)),
                ('total_data_in_file', models.PositiveIntegerField(default=0)),
                ('succeed_data_entry', models.PositiveIntegerField(default=0)),
                ('failed_data_entry', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('fail', 'Fail')], default='in_progress', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Limit Upload Log',
                'ordering': ('-id',),
            },
        ),
    ]
