# Generated by Django 3.1.1 on 2022-01-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0003_limituploadlog'),
        ('rttlimitManagement', '0003_auto_20211227_0941'),
    ]

    operations = [
    ]
