# Generated by Django 3.1.1 on 2021-12-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0003_limituploadlog'),
        ('rttlimitManagement', '0003_auto_20211227_0941'),
    ]

    operations = [
    ]
