# Generated by Django 3.1.1 on 2022-01-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0004_merge_20220105_0507'),
        ('rttlimitManagement', '0004_merge_20211228_0541'),
    ]

    operations = [
    ]
