# Generated by Django 3.1.1 on 2022-03-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0005_merge_20220107_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limituploadlog',
            name='process_type',
            field=models.CharField(choices=[('regulation_substance_limit', 'Regulation Substance Limit'), ('exemption', 'Exemption'), ('limit_additional_attribute_value', 'Limit Additional Attribute Value')], default='regulation_substance_limit', max_length=100),
        ),
    ]
