# Generated by Django 3.1.1 on 2022-04-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0006_auto_20220311_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limituploadlog',
            name='process_type',
            field=models.CharField(choices=[('regulation_substance_limit', 'Regulation Substance Limit'), ('exemption', 'Exemption'), ('limit_additional_attribute_value', 'Limit Additional Attribute Value'), ('limit_with_additional_attribute_value', 'Limit with Additional Attribute Value')], default='regulation_substance_limit', max_length=100),
        ),
    ]
