# Generated by Django 3.1.1 on 2022-04-08 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0006_auto_20220311_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationsubstancelimit',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
