# Generated by Django 3.1.1 on 2022-06-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttlimitManagement', '0007_auto_20220408_0826'),
        ('rttlimitManagement', '0007_auto_20220421_0346'),
        ('rttlimitManagement', '0008_auto_20220526_1146'),
    ]

    operations = [
    ]
