# Generated by Django 3.1.1 on 2020-10-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/material_category_image'),
        ),
    ]
