# Generated by Django 3.1.1 on 2020-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttproduct', '0002_auto_20201023_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='materialcategory',
            constraint=models.UniqueConstraint(fields=('name', 'industry'), name='unique_material_category'),
        ),
    ]
