# Generated by Django 3.1.1 on 2021-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0012_auto_20210224_0645'),
        ('rttproduct', '0004_auto_20201222_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='industry_topics', to='rttregulation.Topic'),
        ),
    ]
