# Generated by Django 3.1.1 on 2021-09-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0001_initial'),
        ('rttproduct', '0005_industry_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='substances',
            field=models.ManyToManyField(blank=True, related_name='substances_product', to='rttsubstance.Substance'),
        ),
    ]
