# Generated by Django 3.1.1 on 2022-04-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttproduct', '0006_product_substances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_product_name_organization'),
        ),
    ]
