# Generated by Django 3.1.1 on 2023-02-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0022_auto_20230110_0624'),
        ('rttproduct', '0008_auto_20220623_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='substance_use_and_apps',
            field=models.ManyToManyField(blank=True, related_name='product_substance_use_and_apps', to='rttsubstance.SubstanceUsesAndApplication'),
        ),
    ]
