# Generated by Django 3.1.1 on 2020-10-21 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0001_initial'),
        ('rttregulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryFrameworkRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rttorganization.organization')),
                ('regulatory_framework', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='regulatory_framework_rating', to='rttregulation.regulatoryframework')),
            ],
            options={
                'ordering': ('rating',),
            },
        ),
        migrations.CreateModel(
            name='RegulationRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rttorganization.organization')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='regulation_rating', to='rttregulation.regulation')),
            ],
            options={
                'ordering': ('rating',),
            },
        ),
    ]
