# Generated by Django 3.1.1 on 2020-11-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rttdocument', '0001_initial'),
        ('rttregulation', '0002_regulationrating_regulatoryframeworkrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='regulation',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='regulation_documents', to='rttdocument.Document'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='regulation_status', to='rttregulation.status'),
        ),
    ]
