# Generated by Django 3.1.1 on 2020-12-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0004_answer_regulatory_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='regulatoryframework',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
