# Generated by Django 3.1.1 on 2020-12-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0005_auto_20201217_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulationmilestone',
            options={'ordering': ('created',), 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AddConstraint(
            model_name='regulationmilestone',
            constraint=models.UniqueConstraint(fields=('name', 'regulation'), name='unique_regulation_milestone'),
        ),
        migrations.AddConstraint(
            model_name='regulationmilestone',
            constraint=models.UniqueConstraint(fields=('name', 'regulatory_framework'), name='unique_framework_milestone'),
        ),
    ]
