# Generated by Django 3.1.1 on 2021-01-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0008_issuingbody_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuingbody',
            name='urls',
        ),
        migrations.AddField(
            model_name='issuingbody',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
