# Generated by Django 3.1.1 on 2021-01-07 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttregulation', '0009_auto_20210104_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
