# Generated by Django 3.1.1 on 2021-06-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0013_auto_20210525_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
