# Generated by Django 3.1.1 on 2021-08-26 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


def forwards(apps, schema_editor):
    RegulationRatingLog = apps.get_model('rttregulation', 'regulationratinglog')
    RegulationRating = apps.get_model('rttregulation', 'regulationrating')

    rating_list = RegulationRating.objects.all()
    RegulationRatingLog.objects.bulk_create(
        RegulationRatingLog(organization=x.organization,
                            regulation=x.regulation,
                            rating=x.rating,
                            comment=x.comment,
                            user=x.user)
        for x in rating_list
    )

    RegulationRating.objects.all().delete()
    rating_list = RegulationRatingLog.objects.all().distinct('organization_id', 'regulation_id') \
        .order_by('organization_id', 'regulation_id', '-created')

    RegulationRating.objects.bulk_create(
        RegulationRating(organization=x.organization,
                         regulation=x.regulation,
                         rating=x.rating,
                         comment=x.comment,
                         user=x.user)
        for x in rating_list
    )


class Migration(migrations.Migration):
    dependencies = [
        ('rttorganization', '0008_organization_industries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttregulation', '0014_auto_20210609_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationRatingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rttorganization.organization')),
                ('regulation',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='regulation_rating_log',
                                   to='rttregulation.regulation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('rating',),
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
