# Generated by Django 3.1.1 on 2021-09-09 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0001_initial'),
        ('rttregulation', '0014_auto_20210609_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='substances',
            field=models.ManyToManyField(blank=True, related_name='substances_regulation', to='rttsubstance.Substance'),
        ),
        migrations.AddField(
            model_name='regulationmilestone',
            name='substances',
            field=models.ManyToManyField(blank=True, related_name='substances_regulation_milestone', to='rttsubstance.Substance'),
        ),
        migrations.AddField(
            model_name='regulatoryframework',
            name='substances',
            field=models.ManyToManyField(blank=True, related_name='substances_regulatory_framework', to='rttsubstance.Substance'),
        ),
        migrations.CreateModel(
            name='SubstanceRegulatoryFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('regulatory_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_framework_substance_relation', to='rttregulation.regulatoryframework')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_regulatory_framework_relation', to='rttsubstance.substance')),
            ],
            options={
                'verbose_name_plural': 'Substance RegulatoryFramework',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SubstanceRegulationMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('regulation_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_milestone_substance_relation', to='rttregulation.regulationmilestone')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_regulation_milestone_relation', to='rttsubstance.substance')),
            ],
            options={
                'verbose_name_plural': 'Substance RegulationMilestone',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SubstanceRegulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_substance_relation', to='rttregulation.regulation')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_regulation_relation', to='rttsubstance.substance')),
            ],
            options={
                'verbose_name_plural': 'Substance Regulation',
                'ordering': ('-id',),
            },
        ),
        migrations.AddConstraint(
            model_name='substanceregulatoryframework',
            constraint=models.UniqueConstraint(fields=('substance', 'regulatory_framework'), name='unique_substance_regulatory_framework'),
        ),
        migrations.AddConstraint(
            model_name='substanceregulationmilestone',
            constraint=models.UniqueConstraint(fields=('substance', 'regulation_milestone'), name='unique_substance_regulation_milestone'),
        ),
        migrations.AddConstraint(
            model_name='substanceregulation',
            constraint=models.UniqueConstraint(fields=('substance', 'regulation'), name='unique_substance_regulation'),
        ),
    ]
