# Generated by Django 3.1.1 on 2021-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0014_auto_20210609_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='text',
            field=models.TextField(),
        ),
    ]
