# Generated by Django 3.1.1 on 2021-09-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0015_auto_20210818_1106'),
        ('rttregulation', '0015_auto_20210909_1153'),
    ]

    operations = [
    ]
