# Generated by Django 3.1.1 on 2021-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0015_auto_20210818_1106'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regulationmilestone',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('regulation__isnull', False), ('regulatory_framework__isnull', True)), models.Q(('regulation__isnull', True), ('regulatory_framework__isnull', False)), _connector='OR'), name='only_regulation_or_regulatory_framework'),
        ),
    ]
