# Generated by Django 3.1.1 on 2021-08-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


def forwards(apps, schema_editor):
    RegulatoryFrameworkRatingLog = apps.get_model('rttregulation', 'regulatoryframeworkratinglog')
    RegulatoryFrameworkRating = apps.get_model('rttregulation', 'regulatoryframeworkrating')

    rating_list = RegulatoryFrameworkRating.objects.all()
    RegulatoryFrameworkRatingLog.objects.bulk_create(
        RegulatoryFrameworkRatingLog(organization=x.organization,
                                     regulatory_framework=x.regulatory_framework,
                                     rating=x.rating,
                                     comment=x.comment,
                                     user=x.user)
        for x in rating_list
    )

    RegulatoryFrameworkRating.objects.all().delete()
    rating_list = RegulatoryFrameworkRatingLog.objects.all().distinct('organization_id', 'regulatory_framework_id') \
        .order_by('organization_id', 'regulatory_framework_id', '-created')

    RegulatoryFrameworkRating.objects.bulk_create(
        RegulatoryFrameworkRating(organization=x.organization,
                                  regulatory_framework=x.regulatory_framework,
                                  rating=x.rating,
                                  comment=x.comment,
                                  user=x.user)
        for x in rating_list
    )


class Migration(migrations.Migration):
    dependencies = [
        ('rttorganization', '0009_auto_20210810_0658'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttregulation', '0016_auto_20210826_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryFrameworkRatingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rttorganization.organization')),
                ('regulatory_framework', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                           related_name='regulatory_framework_rating_log',
                                                           to='rttregulation.regulatoryframework')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('rating',),
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
