# Generated by Django 3.1.1 on 2021-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0017_regulatoryframeworkratinglog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='regulatoryframeworkrating',
            constraint=models.UniqueConstraint(fields=('organization', 'regulatory_framework'), name='unique_regulatory_framework_organization_relevancy'),
        ),
    ]
