# Generated by Django 3.1.1 on 2021-09-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0016_auto_20210920_0849'),
        ('rttregulation', '0018_auto_20210826_1302'),
    ]

    operations = [
    ]
