# Generated by Django 3.1.1 on 2021-09-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0016_merge_20210910_1024'),
        ('rttregulation', '0019_merge_20210920_1224'),
    ]

    operations = [
    ]
