# Generated by Django 3.1.1 on 2021-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0021_auto_20211013_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='publish_limit_data',
            field=models.BooleanField(default=False, help_text='Decides if the limit data should be published to frontend'),
        ),
        migrations.AddField(
            model_name='regulatoryframework',
            name='publish_limit_data',
            field=models.BooleanField(default=False, help_text='Decides if the limit data should be published to frontend'),
        ),
    ]
