# Generated by Django 3.1.1 on 2022-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0022_auto_20211201_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationratinglog',
            name='prev_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryframeworkratinglog',
            name='prev_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
