# Generated by Django 3.1.1 on 2022-04-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0023_auto_20220425_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rttregulation.region'),
        ),
    ]
