# Generated by Django 3.1.1 on 2022-03-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0023_auto_20220303_1332'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('regulation__isnull', False), ('regulatory_framework__isnull', True)), models.Q(('regulation__isnull', True), ('regulatory_framework__isnull', False)), _connector='OR'), name='only_regulation_or_regulatory_framework_in_answer'),
        ),
    ]
