# Generated by Django 3.1.1 on 2022-04-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0024_auto_20220425_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='regulation_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='regulation_longitude',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='region',
            name='news_latitude',
        ),
        migrations.RemoveField(
            model_name='region',
            name='news_longitude',
        ),
    ]
