# Generated by Django 3.1.1 on 2022-04-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0024_auto_20220318_1020'),
        ('rttregulation', '0024_auto_20220314_0521'),
    ]

    operations = [
    ]
