# Generated by Django 3.1.1 on 2022-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0025_merge_20220418_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country_flag',
            field=models.FileField(blank=True, null=True, upload_to='media/region'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_page',
            field=models.BooleanField(default=False),
        ),
    ]
