# Generated by Django 3.1.1 on 2022-05-12 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttorganization', '0012_merge_20211221_1319'),
        ('rttregulation', '0025_merge_20220418_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationMute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_muted', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_mute_org', to='rttorganization.organization')),
                ('regulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulation_mute_regulation', to='rttregulation.regulation')),
                ('regulatory_framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulation_mute_framework', to='rttregulation.regulatoryframework')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddConstraint(
            model_name='regulationmute',
            constraint=models.UniqueConstraint(fields=('organization', 'regulation'), name='unique_org_regulation_regulation_mute'),
        ),
        migrations.AddConstraint(
            model_name='regulationmute',
            constraint=models.UniqueConstraint(fields=('organization', 'regulatory_framework'), name='unique_org_framework_regulation_mute'),
        ),
        migrations.AddConstraint(
            model_name='regulationmute',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('regulation__isnull', False), ('regulatory_framework__isnull', True)), models.Q(('regulation__isnull', True), ('regulatory_framework__isnull', False)), _connector='OR'), name='only_regulation_or_regulatory_framework_in_user_regulation_mute'),
        ),
    ]
