# Generated by Django 3.1.1 on 2022-06-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0025_auto_20220428_0421'),
        ('rttregulation', '0026_auto_20220531_0951'),
    ]

    operations = [
    ]
