# Generated by Django 3.1.1 on 2022-08-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0026_auto_20220512_0354'),
        ('rttregulation', '0028_auto_20220801_1226'),
    ]

    operations = [
    ]
