# Generated by Django 3.1.1 on 2022-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttproduct', '0007_auto_20220425_0812'),
        ('rttregulation', '0028_auto_20220801_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='region_industries', to='rttproduct.Industry'),
        ),
    ]
