# Generated by Django 3.1.1 on 2022-09-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0029_merge_20220804_0451'),
        ('rttregulation', '0029_region_industries'),
    ]

    operations = [
    ]
