# Generated by Django 3.1.1 on 2022-09-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0030_merge_20220914_0553'),
        ('rttregulation', '0030_auto_20220824_1937'),
    ]

    operations = [
    ]
