# Generated by Django 3.1.1 on 2023-03-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0031_merge_20220916_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rttregulation.regulation'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='regulatory_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rttregulation.regulatoryframework'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='regulatory_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulation_regulatory_framework', to='rttregulation.regulatoryframework'),
        ),
        migrations.AlterField(
            model_name='regulationmilestone',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulation_milestone', to='rttregulation.regulation'),
        ),
        migrations.AlterField(
            model_name='regulationmilestone',
            name='regulatory_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_framework_milestone', to='rttregulation.regulatoryframework'),
        ),
        migrations.AlterField(
            model_name='regulationrating',
            name='regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_rating', to='rttregulation.regulation'),
        ),
        migrations.AlterField(
            model_name='regulationratinglog',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulation_rating_log', to='rttregulation.regulation'),
        ),
        migrations.AlterField(
            model_name='regulatoryframeworkrating',
            name='regulatory_framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_framework_rating', to='rttregulation.regulatoryframework'),
        ),
        migrations.AlterField(
            model_name='regulatoryframeworkratinglog',
            name='regulatory_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_framework_rating_log', to='rttregulation.regulatoryframework'),
        ),
    ]
