# Generated by Django 3.1.1 on 2020-10-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0002_auto_20201022_2303'),
        ('rttauth', '0002_auto_20201019_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_user', to='rttorganization.organization'),
        ),
    ]
