# Generated by Django 3.1.1 on 2020-11-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0004_auto_20201105_1114'),
        ('rttauth', '0003_auto_20201022_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_user', to='rttorganization.organization'),
        ),
    ]
