# Generated by Django 3.1.1 on 2020-12-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttauth', '0004_auto_20201105_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Organization admin status'),
        ),
    ]
