# Generated by Django 3.1.1 on 2020-12-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttauth', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
