# Generated by Django 3.1.1 on 2020-12-22 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttorganization', '0007_auto_20201217_1347'),
        ('rttauth', '0006_auto_20201217_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('deleted', 'Deleted')], default='created', max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invite_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invite_organization', to='rttorganization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
