# Generated by Django 3.1.1 on 2021-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttauth', '0008_auto_20210105_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
