# Generated by Django 3.1.1 on 2021-12-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttauth', '0013_auto_20211027_0804'),
        ('rttauth', '0013_auto_20210929_0725'),
    ]

    operations = [
    ]
