# Generated by Django 3.1.1 on 2021-11-17 09:06

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0002_auto_20210929_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceUploadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file_name', models.TextField()),
                ('process_type', models.CharField(choices=[('substance_basic_details', 'Substance Basic Details'), ('substances_with_uses_and_applications', 'Substances with Uses and Applications'), ('substance_related_products', 'Substance Related Products'), ('substance_data', 'Substance Data'), ('substances_in_Regulatory_frameworks_or_Regulations', 'Substances in Regulatory Frameworks/Regulations')], default='substance_basic_details', max_length=100)),
                ('total_data_in_file', models.PositiveIntegerField(default=0)),
                ('succeed_data_entry', models.PositiveIntegerField(default=0)),
                ('failed_data_entry', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], default='success', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Substance Upload Log',
                'db_table': 'rttsubstance_substance_upload_log',
                'ordering': ('-id',),
            },
        ),
    ]
