# Generated by Django 3.1.1 on 2021-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0003_substanceuploadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='substanceuploadlog',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
