# Generated by Django 3.1.1 on 2021-12-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0005_auto_20211119_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substanceuploadlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('in_progress', 'In Progress'), ('fail', 'Fail')], default='in_progress', max_length=20),
        ),
    ]
