# Generated by Django 3.1.1 on 2021-12-01 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0005_auto_20211119_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='is_family',
            field=models.BooleanField(default=False, help_text='Define this substance as a family'),
        ),
        migrations.CreateModel(
            name='SubstanceFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('family_source', models.TextField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='rttsubstance.substance')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance', to='rttsubstance.substance')),
            ],
            options={
                'verbose_name_plural': 'Substance families',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='substance',
            name='families',
            field=models.ManyToManyField(blank=True, related_name='_substance_families_+', through='rttsubstance.SubstanceFamily', to='rttsubstance.Substance'),
        ),
        migrations.AddConstraint(
            model_name='substancefamily',
            constraint=models.UniqueConstraint(fields=('substance', 'family'), name='unique_substance_family'),
        ),
    ]
