# Generated by Django 3.1.1 on 2021-12-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0006_auto_20211202_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='name',
            field=models.TextField(),
        ),
    ]
