# Generated by Django 3.1.1 on 2021-12-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0006_auto_20211202_0617'),
        ('rttsubstance', '0006_auto_20211201_0644'),
    ]

    operations = [
    ]
