# Generated by Django 3.1.1 on 2021-12-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0007_auto_20211215_1053'),
        ('rttsubstance', '0007_merge_20211210_1557'),
    ]

    operations = [
    ]
