# Generated by Django 3.1.1 on 2021-12-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0007_auto_20211202_1645'),
        ('rttsubstance', '0007_auto_20211215_1053'),
    ]

    operations = [
    ]
