# Generated by Django 3.1.1 on 2021-12-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0009_merge_20211228_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substanceuploadlog',
            name='process_type',
            field=models.CharField(choices=[('substance_basic_details', 'Substance Basic Details'), ('substances_with_uses_and_applications', 'Substances with Uses and Applications'), ('substance_related_products', 'Substance Related Products'), ('substance_data', 'Substance Data'), ('substances_in_Regulatory_frameworks_or_Regulations', 'Substances in Regulatory Frameworks/Regulations'), ('substance_families', 'Substance families')], default='substance_basic_details', max_length=100),
        ),
    ]
