# Generated by Django 3.1.1 on 2021-12-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0008_merge_20211220_0752'),
        ('rttsubstance', '0010_auto_20211228_0401'),
    ]

    operations = [
    ]
