# Generated by Django 3.1.1 on 2022-01-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0008_merge_20211220_0752'),
        ('rttsubstance', '0010_auto_20211228_0401'),
    ]

    operations = [
    ]
