# Generated by Django 3.1.1 on 2022-01-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0011_merge_20220105_0508'),
        ('rttsubstance', '0011_merge_20211228_0540'),
    ]

    operations = [
    ]
