# Generated by Django 3.1.1 on 2022-03-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0012_merge_20220107_0633'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='substanceusesandapplication',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_substance_name_organization'),
        ),
    ]
