# Generated by Django 3.1.1 on 2022-03-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0013_auto_20220318_0705'),
        ('rttsubstance', '0013_auto_20220315_0859'),
    ]

    operations = [
    ]
