# Generated by Django 3.1.1 on 2022-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0014_merge_20220330_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubstanceaddlog',
            old_name='uses_and_application',
            new_name='object_ids',
        ),
        migrations.AddField(
            model_name='usersubstanceaddlog',
            name='object_type',
            field=models.CharField(choices=[('uses_and_application', 'Uses And Application')], default='uses_and_application', max_length=100),
        ),
    ]
