# Generated by Django 3.1.1 on 2022-05-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0015_auto_20220401_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substanceuploadlog',
            name='status',
            field=models.CharField(choices=[('in_queue', 'In Queue'), ('success', 'Success'), ('in_progress', 'In Progress'), ('fail', 'Fail')], default='in_progress', max_length=20),
        ),
    ]
