# Generated by Django 3.1.1 on 2022-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0016_auto_20220513_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='substancepropertydatapoint',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
