# Generated by Django 3.1.1 on 2022-09-13 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0017_substancepropertydatapoint_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='substancepropertydatapoint',
            name='unique_substance_property_data_point',
        ),
        migrations.AlterField(
            model_name='substancepropertydatapoint',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='substancepropertydatapoint',
            name='property_data_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_property_data_point_property_data_point', to='rttsubstance.propertydatapoint'),
        ),
        migrations.AlterField(
            model_name='substanceuploadlog',
            name='process_type',
            field=models.CharField(choices=[('substance_basic_details', 'Substance Basic Details'), ('substances_with_uses_and_applications', 'Substances with Uses and Applications'), ('substance_related_products', 'Substance Related Products'), ('substance_data', 'Substance Data'), ('substances_in_Regulatory_frameworks_or_Regulations', 'Substances in Regulatory Frameworks/Regulations'), ('substance_families', 'Substance families'), ('admin_substance_data', 'Admin Substance Data')], default='substance_basic_details', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='substancepropertydatapoint',
            constraint=models.UniqueConstraint(condition=models.Q(status='active'), fields=('substance', 'property_data_point', 'status'), name='unique_substance_property_data_point'),
        ),
    ]
