# Generated by Django 3.1.1 on 2022-11-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0018_auto_20221027_0653'),
        ('rttsubstance', '0018_auto_20220913_1250'),
    ]

    operations = [
    ]
