# Generated by Django 3.1.1 on 2022-12-01 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0019_merge_20221118_1017'),
        ('rttsubstance', '0017_auto_20220929_1024'),
    ]

    operations = [
    ]
