# Generated by Django 3.1.1 on 2022-12-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0020_merge_20221201_0531'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prioritizationstrategy',
            name='unique_organization_strategy',
        ),
        migrations.AlterField(
            model_name='substanceuploadlog',
            name='process_type',
            field=models.CharField(choices=[('substance_basic_details', 'Substance Basic Details'), ('substances_with_uses_and_applications', 'Substances with Uses and Applications'), ('substance_related_products', 'Substance Related Products'), ('substance_data', 'Substance Data'), ('substances_in_Regulatory_frameworks_or_Regulations', 'Substances in Regulatory Frameworks/Regulations'), ('substance_families', 'Substance families'), ('admin_substance_data', 'Admin Substance Data'), ('admin_substance_families', 'Admin substance families')], default='substance_basic_details', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='prioritizationstrategy',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_organization_strategy'),
        ),
    ]
