# Generated by Django 3.1.1 on 2023-02-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttsubstance', '0022_auto_20230110_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substanceuploadlog',
            name='process_type',
            field=models.CharField(choices=[('substance_basic_details', 'Substance Basic Details'), ('substances_with_uses_and_applications', 'Substances with Uses and Applications'), ('substance_related_products', 'Substance Related Products'), ('substance_data', 'Substance Data'), ('substances_in_Regulatory_frameworks_or_Regulations', 'Substances in Regulatory Frameworks/Regulations'), ('substance_families', 'Substance families'), ('admin_substance_data', 'Admin Substance Data'), ('admin_substance_families', 'Admin substance families'), ('substance_data_with_existing_data_decision', 'Substance Data With Existing Data Decision')], default='substance_basic_details', max_length=100),
        ),
    ]
