# Generated by Django 3.1.1 on 2020-12-15 07:53

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttregulation', '0004_answer_regulatory_framework'),
        ('rttdocument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('faq', 'faq'), ('documents', 'documents')], default='faq', max_length=10)),
                ('links', models.ManyToManyField(blank=True, related_name='doc_faq_links', to='rttregulation.Url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
