# Generated by Django 3.1.1 on 2020-12-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttdocument', '0002_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='links',
        ),
        migrations.AddField(
            model_name='help',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='help_documents', to='rttdocument.Document'),
        ),
    ]
