# Generated by Django 3.1.1 on 2020-12-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttdocument', '0003_auto_20201215_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, related_name='help_documents', to='rttdocument.Document'),
        ),
    ]
