# Generated by Django 3.1.1 on 2021-01-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttdocument', '0005_auto_20201217_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='documents',
        ),
        migrations.AddField(
            model_name='help',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/help_docs'),
        ),
    ]
