# Generated by Django 3.1.1 on 2022-02-22 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttnotification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskEmailReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task_type', models.CharField(choices=[('all', 'All'), ('fetch_news', 'Fetch News')], default='all', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_celery_task_email_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Celery Task Email Receiver',
                'ordering': ('-created',),
            },
        ),
        migrations.AddConstraint(
            model_name='celerytaskemailreceiver',
            constraint=models.UniqueConstraint(fields=('user', 'task_type'), name='unique_user_task_type'),
        ),
    ]
