# Generated by Django 3.1.1 on 2022-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttnotification', '0002_auto_20220222_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationalert',
            name='content',
            field=models.CharField(choices=[('news', 'News'), ('regulatory_updates', 'Regulatory updates'), ('assessments', 'Assessments'), ('limit', 'Limit'), ('substance', 'Substance')], max_length=255),
        ),
    ]
