# Generated by Django 3.1.1 on 2022-09-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rttnotification', '0003_auto_20220811_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationalert',
            name='content',
            field=models.CharField(choices=[('news', 'News'), ('regulatory_updates', 'Regulatory updates'), ('assessments', 'Assessments'), ('limits', 'Limits'), ('substances', 'Substances')], max_length=255),
        ),
    ]
