# Generated by Django 3.1.1 on 2022-01-18 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rttproduct', '0006_product_substances'),
        ('rttregulation', '0022_auto_20211201_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_assignee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='task_related_products', to='rttproduct.Product')),
                ('regulations', models.ManyToManyField(blank=True, related_name='task_regulations', to='rttregulation.Regulation')),
                ('regulatory_frameworks', models.ManyToManyField(blank=True, related_name='task_regulatory_frameworks', to='rttregulation.RegulatoryFramework')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
