# Generated by Django 3.1.1 on 2022-01-21 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rttnews', '0012_merge_20210921_1324'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtttaskManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('created',), 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='news',
            field=models.ManyToManyField(blank=True, related_name='task_news', to='rttnews.News'),
        ),
        migrations.CreateModel(
            name='TaskEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtttaskManagement.task')),
            ],
            options={
                'verbose_name_plural': 'Task editors',
                'ordering': ('created',),
            },
        ),
        migrations.AddConstraint(
            model_name='taskeditor',
            constraint=models.UniqueConstraint(fields=('task', 'editor'), name='unique_task_editor'),
        ),
    ]
