# Generated by Django 3.1.1 on 2022-03-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtttaskManagement', '0003_auto_20220302_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
