# Generated by Django 3.1.1 on 2022-03-09 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtttaskManagement', '0003_auto_20220302_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action', models.CharField(choices=[('created', 'Created'), ('changed', 'Changed'), ('assigned', 'Assigned')], default='changed', max_length=20)),
                ('action_field', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_value', models.TextField(blank=True, null=True)),
                ('curr_value', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('action_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtttaskManagement.task')),
            ],
            options={
                'verbose_name_plural': 'Task history',
                'ordering': ('created',),
            },
        ),
    ]
