# Generated by Django 3.1.1 on 2022-04-25 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtttaskManagement', '0004_task_is_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comment_text', models.TextField()),
                ('edited', models.DateTimeField(blank=True, default=None, null=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_comment_by', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comment', to='rtttaskManagement.task')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
