# Generated by Django 3.1.1 on 2022-04-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtttaskManagement', '0004_taskhistory'),
        ('rtttaskManagement', '0004_task_is_archive'),
    ]

    operations = [
    ]
