# Generated by Django 3.1.1 on 2022-05-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtttaskManagement', '0005_taskcomment'),
        ('rtttaskManagement', '0005_merge_20220418_0949'),
    ]

    operations = [
    ]
